var that=this;function __skpm_run(e,t){that.context=t;var n=function(e){var t={};function n(r){if(t[r])return t[r].exports;var u=t[r]={i:r,l:!1,exports:{}};return e[r].call(u.exports,u,u.exports,n),u.l=!0,u.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var u in e)n.d(r,u,function(t){return e[t]}.bind(null,u));return r},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s="./src/my-command.js")}({"./src/my-command.js":
/*!***************************!*\
  !*** ./src/my-command.js ***!
  \***************************/
/*! exports provided: default */function(e,t,n){"use strict";n.r(t);var r=n(/*! sketch */"sketch"),u=n.n(r),o=(n(/*! sketch/dom */"sketch/dom").Document,0);t.default=function(e){var t=u.a.fromNative(e.document),n=t?t.selectedLayers:null;!((n=n?n.layers:null)&&n[0]&&n[0].type&&"Artboard"==n[0].type)?u.a.UI.message("Please select an artboard"):(n=n[0].layers,i(n))};var i=function e(t){t.reverse();for(var n=0;n<t.length;){var r=t[n];n==t.length-1&&c(r)&&(!0,o=p(r)),l(r),n!=t.length-1||c(r)||(!1,o=0),f(r)&&(e(r.layers),r.adjustToFit()),n++}t.reverse()},a=function(e,t){return e%t<t/2?e+(t-e%t)-t:e+(t-e%t)},f=function(e){return"Group"==e.type},c=function(e){return"Text"==e.type},l=function(e){var t=s(e),n=d(e)+t;if(c(e)){var r=(n-=a(m(e),1))+e.frame.height-p(e);n-=r-a(r,4)}e.frame.y=n},s=function(e){var t=e.name,n=t&&t.split("[margin:")?t.split("[margin:")[1]:void 0;return(n=n&&n.split("]")?n.split("]")[0]:void 0)?Number(n):0},d=function(e){var t=e.index,n=0;if(t>0){var r=e.parent.layers[t-1];n=r.frame.y+r.frame.height,n-=p(r),"Group"==r.type&&(n-=o)}return v(e)?0:n},p=function(e){if(c(e)){var t=y(e),n=a(.4289721168*t,1);return 1.5*e.style.fontSize==e.style.lineHeight?n+=1:24==e.style.fontSize&&32==e.style.lineHeight&&(n+=1),n}return 0},y=function(e){return e.style.lineHeight-function(e){return.713984375*e.style.fontSize}(e)},m=function(e){return.5710278832*y(e)},v=function(e){if(e.name&&e.name.includes("[top]"))return!0}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("sketch")},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/dom")}});"default"===e&&"function"==typeof n?n(t):n[e](t)}that.onRun=__skpm_run.bind(this,"default");